site_name: Kurve docs
#repo_url: https://github.com/kurveai/kurvedocs
#repo_name: kurvedocs
edit_uri: edit/main/docs

theme:
  name: material
  favicon: images/Kurve_Logotype_04.png
  logo: images/Kurve_Logotype_04.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - navigation.expand
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: switch to dark mode

    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: switch to light mode

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Examples: examples.md
  - Snowflake native app: snowflake.md
  - Tutorials: tutorials.md

plugins:
  - search
  - git-revision-date-localized
  - autorefs

markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences

